export const CHANNELS = {
  OPEN_FOLDER: 'dialog:openFolder',
  FILE_EXISTS: 'fs:fileExists',
  LIST_RECENT_FILES: 'fs:listRecentFiles',
  LIST_TREE: 'fs:listTree',
  EXPLAIN_REPO: 'llm:explainRepo',
  EXPLAIN_FILE: 'llm:explainFile',
  EXPLAIN_CHUNK: 'llm:chunk',
  EXPLAIN_DONE: 'llm:done',
  EXPLAIN_ERROR: 'llm:error',
  CHAT_SEND: 'chat:send',
  CHAT_STOP: 'chat:stop',
  CHAT_EVENT: 'chat:event',
  CHAT_DONE: 'chat:done',
  CHAT_ERROR: 'chat:error',
} as const;
